# Generated by Django 5.2.2 on 2025-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=100)),
                ('expires_in', models.IntegerField()),
                ('scope', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
    ]
